### ISSUE TITLE
windows_auth_python_sample.py KeyError: 'items'

### ISSUE THREAD

**Issue by discentem** [GoogleCloudPlatform/compute-image-windows#136]
The script, as is, fails on a KeyError. Trying to troubleshoot, but I figured I'd bring it to your attention. 

Additionally, it would be wicked if there could be an example of this script using the Go API. Can I/Should I open a separate issue for that? 

```
$ python windows_auth_python_sample.py

Traceback (most recent call last):
  File "windows_auth_python_sample.py", line 187, in <module>
    main(instance, zone, project, user, email)
  File "windows_auth_python_sample.py", line 172, in main
    password = DecryptPassword(enc_password, key)
  File "windows_auth_python_sample.py", line 132, in DecryptPassword
    decoded_password = base64.b64decode(encrypted_password)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None
C02SXAM0GTF1:gcp-go-metadata brandon.kurtz$ python windows_auth_python_sample.py
Traceback (most recent call last):
  File "windows_auth_python_sample.py", line 181, in <module>
    main(instance, zone, project, user, email)
  File "windows_auth_python_sample.py", line 153, in main
    new_metadata = UpdateWindowsKeys(old_metadata, metadata_entry)
  File "windows_auth_python_sample.py", line 94, in UpdateWindowsKeys
    for item in new_metadata['items']:
KeyError: 'items'
```

**Comment by adjackura** [comment]
I've been meaning to write a Go example, create another issue and I'll take that on.

**Comment by discentem** [comment]
Will do, thanks @adjackura! 

Oh, I guess the Google docs which link to this script don't get auto updated on a merge? 🤔

**Comment by discentem** [comment]
@adjackura How long does it take for the docs to get update from this repo?

**Comment by adjackura** [comment]
It's cached, It'll be updated when I push the change for the Go example
